const express = require("express");
const app = express();
const body_parser = require("body-parser");
const path = require("path");
const mongoose = require("mongoose");
app.set("views", path.join(__dirname, "./views"));
app.set("view engine", "ejs");
app.use(body_parser.urlencoded({extended: true}));
mongoose.connect("mongodb://localhost/quoting_dojo");
require("./server/models/quote")(mongoose);
require("./server/config/routes")(app);
app.listen(8000);