const express = require("express");
const app = express();
const body_parser = require("body-parser");
const path = require("path");
app.set("views", path.join(__dirname, "./views"));
app.set("view engine", "ejs");
app.use(body_parser.urlencoded({extended: true}));
require("./server/config/mongoose")();
require("./server/config/routes")(app);
app.listen(8000);